version: "3.8"
services:
    db:
        image: mysql
        container_name: nrh_projet_laravel_ecommerce__mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: e_commerce
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            # MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        ports:
            - "3306"
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: nrh_projet_laravel_ecommerce__phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    php:
        image: nrh-php:7.4-apache
        container_name: nrh_projet_laravel_ecommerce__php
        restart: unless-stopped
        volumes:
            - ./:/var/www/project:delegated
            # - ./vhosts/vhosts.conf:/etc/apache2/sites-enable/000-default.conf
            - ./vhosts/vhosts.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - 8080:80
        depends_on:
            - db
        networks:
            - dev

networks:
    dev:
